version: "3"
services:
  rtpproxy:
    container_name: 'rtpproxy'
    image: 'xsdhy/rtpproxy:latest'
    network_mode: host
    environment:
      - SOCKET_ADDR=udp:127.0.0.1:12221
      - MIN_PORT=26000
      - MAX_PORT=30000